# Classification  -  create creativity dataset
   To build a new dataset which focus on the personal factors. 
   
   We have to set a scoring mechanism based on the consumer demand , and this example
   
   will be used to write a new dataframe.

In [98]:
#import models
%matplotlib inline
import numpy as np               #import numpy for cal
import pandas as pd              #import pandas for read file
import matplotlib.pyplot as plt  #import matplotlib to show some graph

In [99]:
names = pd.read_csv('car.c45-names.txt',sep = '\t',encoding = 'utf-8',header=None)            #read file
car_data = pd.read_csv('car.data.txt',sep = ",",encoding = 'utf-8')                           #read file
car_data.columns=["buying", "maint", "doors", "persons", "lug_boot", "safety", "class_values"]#add titles 
car_data['persional_point']='0'#DataFrame add a colume

In [100]:
names   #check the datesets file contains

                                                   0
0  | names file (C4.5 format) for car evaluation ...
1                                     | class values
2                            unacc, acc, good, vgood
3                                       | attributes
4                   buying:   vhigh, high, med, low.
5                   maint:    vhigh, high, med, low.
6                          doors:    2, 3, 4, 5more.
7                              persons:  2, 4, more.
8                         lug_boot: small, med, big.
9                          safety:   low, med, high.

In [101]:
car_data.head() #check raw data

  buying  maint doors persons lug_boot safety class_values persional_point
0  vhigh  vhigh     2       2    small    med        unacc               0
1  vhigh  vhigh     2       2    small   high        unacc               0
2  vhigh  vhigh     2       2      med    low        unacc               0
3  vhigh  vhigh     2       2      med    med        unacc               0
4  vhigh  vhigh     2       2      med   high        unacc               0

## Set the persional point
    In this part , we will set a new score for the new feature .
    Focus on family , so the car must have enough seats . 
    The 'persons' part is most important , so I set the weights '70%' in the persional_point.
    And the second one is 'doors' part. For some family trip , it will be Convenient to have 
    enough doors. I gave it the weights '30%'.
    
   * point1(doors)
     * 2 doors -> 1 
     * 3 doors -> 2 
     * 4 doors -> 3 
     * 5more doors -> 4
     
     <br />
   * point2(persons)
     * 2 people -> 1 
     * 4 people -> 2 
     * more people -> 3 
     
   <br />
   * point_final=0.3*point1+0.7*point2

In [95]:
#adjust the file ,so that we can use the file
for i in range(1727):
    #buying: vhigh, high, med, low.
    #buying: 1, 2, 3, 4.
    if car_data.buying[i]=='vhigh': 
        car_data.buying[i]=1
    elif car_data.buying[i]=='high':
        car_data.buying[i]=2    
    elif car_data.buying[i]=='med':
        car_data.buying[i]=3
    elif car_data.buying[i]=='low':
        car_data.buying[i]=4
        #################################################
        #maint: vhigh, high, med, low
        #maint: 1, 2, 3, 4
    if car_data.maint[i]=='vhigh':
        car_data.maint[i]=1
    elif car_data.maint[i]=='high':
        car_data.maint[i]=2    
    elif car_data.maint[i]=='med':
        car_data.maint[i]=3
    elif car_data.maint[i]=='low':
        car_data.maint[i]=4
        ################################################
        #doors: 2, 3, 4, 5more
        #doors: 2, 3, 4, 5
    if car_data.doors[i]=='5more':
        car_data.doors[i]=5
   
        ###############################################
        #persons: 2, 4, more
        #persons: 2, 4, 6
    if car_data.persons[i]=='more':
        car_data.persons[i]=6
        ##############################################
        #lug_boot: small, med, big.
        #lug_boot: 1, 2, 3.
    if car_data.lug_boot[i]=='small':
        car_data.lug_boot[i]=1
    elif car_data.lug_boot[i]=='med':
        car_data.lug_boot[i]=2    
    elif car_data.lug_boot[i]=='big':
        car_data.lug_boot[i]=3
        #################################################
        #safety: low, med, high.
        #safety: 1, 2, 3.
    if car_data.safety[i]=='low':
        car_data.safety[i]=1
    elif car_data.safety[i]=='med':
        car_data.safety[i]=2    
    elif car_data.safety[i]=='high':
        car_data.safety[i]=3
    
    #persional point
    point1=0
    point2=0
    point_final=0 
    if car_data.doors[i]==2:
        point1=1
    elif car_data.doors[i]==3:
        point1=2   
    elif car_data.doors[i]==4:
        point1=3   
    elif car_data.doors[i]==5:
        point1=4
        
    if car_data.persons[i]==2:
        point2=1
    elif car_data.persons[i]==4:
        point2=2   
    elif car_data.persons[i]==6:
        point2=3    
    
    #point_final=0.3*point1+0.7*point2
    point_final=0.3*point1+0.7*point2
    car_data.persional_point[i]=point_final
#     if point_final<0.4:
#         car_data.persional_point[i]=1
#     elif point_final>=0.4 and  point_final<0.8:
#         car_data.persional_point[i]=2    
#     elif point_final>=0.8 and  point_final<1.2:
#         car_data.persional_point[i]=3  
#     elif point_final>=1.2 and  point_final<1.6:
#         car_data.persional_point[i]=4  
#     elif point_final>=1.6 :
#         car_data.persional_point[i]=5

In [96]:
car_data #check raw data

     buying maint doors persons lug_boot safety class_values persional_point
0         1     1     2       2        1      2        unacc               0
1         1     1     2       2        1      3        unacc               0
2         1     1     2       2        2      1        unacc               0
3         1     1     2       2        2      2        unacc               0
4         1     1     2       2        2      3        unacc               0
5         1     1     2       2        3      1        unacc               0
6         1     1     2       2        3      2        unacc               0
7         1     1     2       2        3      3        unacc               0
8         1     1     2       4        1      1        unacc               0
9         1     1     2       4        1      2        unacc               0
10        1     1     2       4        1      3        unacc               0
11        1     1     2       4        2      1        unacc               0
12        1     1     2       4        2      2        unacc               0
13        1     1     2       4        2      3        unacc               0
14        1     1     2       4        3      1        unacc               0
15        1     1     2       4        3      2        unacc               0
16        1     1     2       4        3      3        unacc               0
17        1     1     2       6        1      1        unacc             2.1
18        1     1     2       6        1      2        unacc             2.1
19        1     1     2       6        1      3        unacc             2.1
20        1     1     2       6        2      1        unacc             2.1
21        1     1     2       6        2      2        unacc             2.1
22        1     1     2       6        2      3        unacc             2.1
23        1     1     2       6        3      1        unacc             2.1
24        1     1     2       6        3      2        unacc             2.1
25        1     1     2       6        3      3        unacc             2.1
26        1     1     3       2        1      1        unacc               0
27        1     1     3       2        1      2        unacc               0
28        1     1     3       2        1      3        unacc               0
29        1     1     3       2        2      1        unacc               0
...     ...   ...   ...     ...      ...    ...          ...             ...
1697      4     4     4       6        3      1        unacc             2.1
1698      4     4     4       6        3      2         good             2.1
1699      4     4     4       6        3      3        vgood             2.1
1700      4     4     5       2        1      1        unacc             1.2
1701      4     4     5       2        1      2        unacc             1.2
1702      4     4     5       2        1      3        unacc             1.2
1703      4     4     5       2        2      1        unacc             1.2
1704      4     4     5       2        2      2        unacc             1.2
1705      4     4     5       2        2      3        unacc             1.2
1706      4     4     5       2        3      1        unacc             1.2
1707      4     4     5       2        3      2        unacc             1.2
1708      4     4     5       2        3      3        unacc             1.2
1709      4     4     5       4        1      1        unacc             1.2
1710      4     4     5       4        1      2          acc             1.2
1711      4     4     5       4        1      3         good             1.2
1712      4     4     5       4        2      1        unacc             1.2
1713      4     4     5       4        2      2         good             1.2
1714      4     4     5       4        2      3        vgood             1.2
1715      4     4     5       4        3      1        unacc             1.2
1716      4     4     5       4        3      2         good             1.2
1717      4     4     5       4        3      3        vgood             1.2
1718      4     4     5       6        1      1        unacc             3.3
1719      4     4     5       6        1      2          acc             3.3
1720      4     4     5       6        1      3         good             3.3
1721      4     4     5       6        2      1        unacc             3.3
1722      4     4     5       6        2      2         good             3.3
1723      4     4     5       6        2      3        vgood             3.3
1724      4     4     5       6        3      1        unacc             3.3
1725      4     4     5       6        3      2         good             3.3
1726      4     4     5       6        3      3        vgood             3.3

[1727 rows x 8 columns]

In [97]:
car_data.to_csv('car_data_creativity.txt') #save the new data